
<CircleButton@Button>
    background_color: (0, 0, 0, 0)
    background_normal: ''
    button_color: (0.33, 0.66, 1, 1)
    canvas.before:
        Color:
            rgba: (1,0,0,.1)
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: self.button_color
        Ellipse:
            pos: root.center_x - min(root.size)*.8/2, root.center_y - min(root.size)*.8/2
            size: min(root.size)*.8, min(root.size)*.8